const assets = [
    {
        position: { lat: -2.184, lng: 100.917 },
        title: "Sodetan",
        millCompanyName: "INCASI RAYA",
        parentCompanyName: "INCASI RAYA",
        address: "Ds.Muara Sakai, Kec.Pancung Soal, Pesisir Selatan, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "12,433 ha",
        ffbProduction: "243,148 ton/year",
        facilityCapacity: "120 ton/hour",
        cpoProduction: "46,626 ton/year",
        pkProduction: "10,341 ton/year",
        description: "농장면적: 12,433 ha, FFB 생산: 243,148 ton/year, 설비 용량: 120 ton/hour, CPO 생산: 46,626 ton/year, PK 생산: 10,341 ton/year. "
    },
    {
        position: { lat: -2.331, lng: 100.995 },
        title: "Silaut",
        millCompanyName: "SUMATERA JAYA AGRO LESTARI",
        parentCompanyName: "INCASI RAYA",
        address: "Ds.Silaut, Kec.Lunang Silaut, Pesisir Selatan, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "10,409 ha",
        ffbProduction: "218,486 ton/year",
        facilityCapacity: "120 ton/hour",
        cpoProduction: "44,846 ton/year",
        pkProduction: "8,925 ton/year",
        description: "농장면적: 10,409 ha, FFB 생산: 218,486 ton/year, 설비 용량: 120 ton/hour, CPO 생산: 44,846 ton/year, PK 생산: 8,925 ton/year."
    },
    {
        position: { lat: -1.393, lng: 101.593 },
        title: "Bina Pratama Sakato Jaya",
        millCompanyName: "BINA PRATAMA SAKATOJAYA",
        parentCompanyName: "INCASI RAYA",
        address: "Nagari Sei Jujuhan, Kec. Sangir Balai Janggo, Kab. Solok Selatan, Propinsi Sumatera Barat",
        province: "SUMATERA BARAT",
        farmArea: "4,095 ha",
        ffbProduction: "64,038 ton/year",
        facilityCapacity: "60 ton/hour",
        cpoProduction: "12,079 ton/year",
        pkProduction: "2,986 ton/year",
        description: "농장면적: 4,095 ha, FFB 생산: 64,038 ton/year, 설비 용량: 60 ton/hour, CPO 생산: 12,079 ton/year, PK 생산: 2,986 ton/year."
    },
    {
        position: { lat: -0.997, lng: 101.742 },
        title: "Sumbar Andalas Kencana",
        millCompanyName: "SUMBAR ANDALAS KENCANA",
        parentCompanyName: "INCASI RAYA",
        address: "Muaro Timpeh, Dharmasraya, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "6,344 ha",
        ffbProduction: "78,224 ton/year",
        facilityCapacity: "60 ton/hour",
        cpoProduction: "15,105 ton/year",
        pkProduction: "2,784 ton/year",
        description: "농장면적: 6,344 ha, FFB 생산: 78,224 ton/year, 설비 용량: 60 ton/hour, CPO 생산: 15,105 ton/year, PK 생산: 2,784 ton/year."
    },
    {
        position: { lat: -1.251, lng: 101.575 },
        title: "Selago Makmur Plantation",
        millCompanyName: "SELAGO MAKMUR PLANTATION",
        parentCompanyName: "INCASI RAYA",
        address: "Sei Rumbai, Dharmasraya, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "6,065 ha",
        ffbProduction: "58,829 ton/year",
        facilityCapacity: "80 ton/hour",
        cpoProduction: "11,701 ton/year",
        pkProduction: "3,140 ton/year",
        description: "농장면적: 6,065 ha, FFB 생산: 58,829 ton/year, 설비 용량: 80 ton/hour, CPO 생산: 11,701 ton/year, PK 생산: 3,140 ton/year."
    },
    {
        position: { lat: 0.362, lng: 99.634 },
        title: "Pasamanan Marahma Sejahtera",
        millCompanyName: "PASAMANAN MARAHMA SEJAHTERA",
        parentCompanyName: "INCASI RAYA",
        address: "Sei Aur, U.Gading, Pasaman Barat, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "4,025 ha",
        ffbProduction: "11,209 ton/year",
        facilityCapacity: "40 ton/hour",
        cpoProduction: "2,145 ton/year",
        pkProduction: "619 ton/year",
        description: "농장면적: 4,025 ha, FFB 생산: 11,209 ton/year, 설비 용량: 40 ton/hour, CPO 생산: 2,145 ton/year, PK 생산: 619 ton/year."
    },
    {
        position: { lat: 0.333, lng: 99.383 },
        title: "Bintara Tani Nusantara",
        millCompanyName: "BINTARA TANI NUSANTARA",
        parentCompanyName: "INCASI RAYA",
        address: "Ds.Jorong Kiawai Timur, Kec.Sungai Beremas, Pasaman Barat, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "7,185 ha",
        ffbProduction: "172,870 ton/year",
        facilityCapacity: "100 ton/hour",
        cpoProduction: "37,769 ton/year",
        pkProduction: "8,315 ton/year",
        description: "농장면적: 7,185 ha, FFB 생산: 172,870 ton/year, 설비 용량: 100 ton/hour, CPO 생산: 37,769 ton/year, PK 생산: 8,315 ton/year."
    },
    {
        position: { lat: -1.320, lng: 101.649 },
        title: "Pangian",
        millCompanyName: "INCASI RAYA",
        parentCompanyName: "INCASI RAYA",
        address: "Sei Rumbai, Dharmasraya, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "6,899 ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "50 ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: 6,899 ha, FFB 생산: (no data) ton/year, 설비 용량: 50 ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year."
    }
];
