const assets = [
    {
        position: { lat: -2.184, lng: 100.917 },
        title: "Sodetan",
        millCompanyName: "INCASI RAYA",
        parentCompanyName: "INCASI RAYA",
        address: "Ds.Muara Sakai, Kec.Pancung Soal, Pesisir Selatan, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "12,433 ha",
        ffbProduction: "243,148 ton/year",
        facilityCapacity: "120 ton/hour",
        cpoProduction: "46,626 ton/year",
        pkProduction: "10,341 ton/year",
        description: "농장면적: 12,433 ha, FFB 생산: 243,148 ton/year, 설비 용량: 120 ton/hour, CPO 생산: 46,626 ton/year, PK 생산: 10,341 ton/year.",
        markerIcon: "palm_tree.png"
    },
    {
        position: { lat: -2.331, lng: 100.995 },
        title: "Silaut",
        millCompanyName: "SUMATERA JAYA AGRO LESTARI",
        parentCompanyName: "INCASI RAYA",
        address: "Ds.Silaut, Kec.Lunang Silaut, Pesisir Selatan, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "10,409 ha",
        ffbProduction: "218,486 ton/year",
        facilityCapacity: "120 ton/hour",
        cpoProduction: "44,846 ton/year",
        pkProduction: "8,925 ton/year",
        description: "농장면적: 10,409 ha, FFB 생산: 218,486 ton/year, 설비 용량: 120 ton/hour, CPO 생산: 44,846 ton/year, PK 생산: 8,925 ton/year.",
        markerIcon: "palm_tree.png"
    },
    {
        position: { lat: -1.393, lng: 101.593 },
        title: "Bina Pratama Sakato Jaya",
        millCompanyName: "BINA PRATAMA SAKATOJAYA",
        parentCompanyName: "INCASI RAYA",
        address: "Nagari Sei Jujuhan, Kec. Sangir Balai Janggo, Kab. Solok Selatan, Propinsi Sumatera Barat",
        province: "SUMATERA BARAT",
        farmArea: "4,095 ha",
        ffbProduction: "64,038 ton/year",
        facilityCapacity: "60 ton/hour",
        cpoProduction: "12,079 ton/year",
        pkProduction: "2,986 ton/year",
        description: "농장면적: 4,095 ha, FFB 생산: 64,038 ton/year, 설비 용량: 60 ton/hour, CPO 생산: 12,079 ton/year, PK 생산: 2,986 ton/year.",
        markerIcon: "palm_tree.png"
    },
    {
        position: { lat: -0.997, lng: 101.742 },
        title: "Sumbar Andalas Kencana",
        millCompanyName: "SUMBAR ANDALAS KENCANA",
        parentCompanyName: "INCASI RAYA",
        address: "Muaro Timpeh, Dharmasraya, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "6,344 ha",
        ffbProduction: "78,224 ton/year",
        facilityCapacity: "60 ton/hour",
        cpoProduction: "15,105 ton/year",
        pkProduction: "2,784 ton/year",
        description: "농장면적: 6,344 ha, FFB 생산: 78,224 ton/year, 설비 용량: 60 ton/hour, CPO 생산: 15,105 ton/year, PK 생산: 2,784 ton/year.",
        markerIcon: "palm_tree.png"
    },
    {
        position: { lat: -1.251, lng: 101.575 },
        title: "Selago Makmur Plantation",
        millCompanyName: "SELAGO MAKMUR PLANTATION",
        parentCompanyName: "INCASI RAYA",
        address: "Sei Rumbai, Dharmasraya, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "6,065 ha",
        ffbProduction: "58,829 ton/year",
        facilityCapacity: "80 ton/hour",
        cpoProduction: "11,701 ton/year",
        pkProduction: "3,140 ton/year",
        description: "농장면적: 6,065 ha, FFB 생산: 58,829 ton/year, 설비 용량: 80 ton/hour, CPO 생산: 11,701 ton/year, PK 생산: 3,140 ton/year.",
        markerIcon: "palm_tree.png"
    },
    {
        position: { lat: 0.362, lng: 99.634 },
        title: "Pasamanan Marahma Sejahtera",
        millCompanyName: "PASAMANAN MARAHMA SEJAHTERA",
        parentCompanyName: "INCASI RAYA",
        address: "Sei Aur, U.Gading, Pasaman Barat, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "4,025 ha",
        ffbProduction: "11,209 ton/year",
        facilityCapacity: "40 ton/hour",
        cpoProduction: "2,145 ton/year",
        pkProduction: "619 ton/year",
        description: "농장면적: 4,025 ha, FFB 생산: 11,209 ton/year, 설비 용량: 40 ton/hour, CPO 생산: 2,145 ton/year, PK 생산: 619 ton/year.",
        markerIcon: "palm_tree.png"
    },
    {
        position: { lat: 0.333, lng: 99.383 },
        title: "Bintara Tani Nusantara",
        millCompanyName: "BINTARA TANI NUSANTARA",
        parentCompanyName: "INCASI RAYA",
        address: "Ds.Jorong Kiawai Timur, Kec.Sungai Beremas, Pasaman Barat, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "7,185 ha",
        ffbProduction: "172,870 ton/year",
        facilityCapacity: "100 ton/hour",
        cpoProduction: "37,769 ton/year",
        pkProduction: "8,315 ton/year",
        description: "농장면적: 7,185 ha, FFB 생산: 172,870 ton/year, 설비 용량: 100 ton/hour, CPO 생산: 37,769 ton/year, PK 생산: 8,315 ton/year.",
        markerIcon: "palm_tree.png"
    },
    {
        position: { lat: -1.320, lng: 101.649 },
        title: "Pangian",
        millCompanyName: "INCASI RAYA",
        parentCompanyName: "INCASI RAYA",
        address: "Sei Rumbai, Dharmasraya, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "6,899 ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "50 ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: 6,899 ha, FFB 생산: (no data) ton/year, 설비 용량: 50 ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "palm_tree.png"
    },
    {
        position: { lat: -2.201, lng: 101.089 },
        title: "Tapan",
        millCompanyName: "KEMILAU PERMATA SAWIT",
        parentCompanyName: "SUPERVENTURE",
        address: "Nagari Kubu Tapan Kec. Basa Ampek Balai Tapan Kab. Pesisir Selatan - West Sumatera",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -0.344148333, lng: 99.96159333 },
        title: "Bukit Sawit Semesta",
        millCompanyName: "BUKIT SAWIT SEMESTA",
        parentCompanyName: "BUKIT SAWIT SEMESTA",
        address: "Agam Sumatera Barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -2.062159, lng: 101.005916 },
        title: "Transco Energi Utama",
        millCompanyName: "PT Transco Energi Utama",
        parentCompanyName: "INCASI RAYA (GUNAS)",
        address: "Jl. Padang - Muko-Muko, Inderapura Sel., Pancung Soal, Kabupaten Pesisir Selatan, Sumatera Barat 25673, Indonesia",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -2.27866, lng: 101.16361 },
        title: "Muara Sawit Lestari",
        millCompanyName: "MUARA SAWIT LESTARI",
        parentCompanyName: "MUARA SAWIT LESTARI",
        address: "Lunang Selatan, Lunang, South Pesisir Regency, West Sumatra, Indonesia",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -0.046138, lng: 99.915697 },
        title: "Gunung Sawit Abadi",
        millCompanyName: "GUNUNG SAWIT ABADI",
        parentCompanyName: "GUNUNG SAWIT ABADI",
        address: "Desa Langgam, Kec. Kinali Kab. Pasaman Barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -1.07924, lng: 101.66442 },
        title: "Dharmasraya Lestarindo",
        millCompanyName: "DHARMASRAYA LESTARINDO",
        parentCompanyName: "DUTA MARGA",
        address: "Nagari Ma Sopan, kec. Padang laweh, kab. Dharmasraya-sumatera barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: 0.224338, lng: 99.715572 },
        title: "Agro Wira Ligatsa",
        millCompanyName: "AGRO WIRA LIGATSA",
        parentCompanyName: "AGRO WIRA LIGATSA",
        address: "jalan jend sudirman, pasaman barat, sumbar",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: 0.238055556, lng: 99.70361111 },
        title: "Berkat Sawit Sejahtera (Pasaman)",
        millCompanyName: "BERKAT SAWIT SEJAHTERA",
        parentCompanyName: "BERKAT SAWIT SEJAHTERA",
        address: "Jl. Simpang Tego Alin RT.000 RW.000 Kec. Gunung Tuleh Kab. Pasaman Barat - West Sumatera",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -0.0229198, lng: 100.002806 },
        title: "Rimbo Panjang Sumber Makmur",
        millCompanyName: "RIMBO PANJANG SUMBER MAKMUR",
        parentCompanyName: "RIMBO PANJANG SUMBER MAKMUR",
        address: "Kec. Kinali, Kab.Pasaman barat, Sumatra barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: 0.305, lng: 99.44721 },
        title: "Usaha Sawit Mandiri",
        millCompanyName: "USAHA SAWIT MANDIRI",
        parentCompanyName: "USAHA SAWIT MANDIRI",
        address: "Jorong Simpang Nagari Parik, Koto Balingka-Pasaman Barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -1.392715, lng: 101.478578 },
        title: "Solok Selatan (PN)",
        millCompanyName: "PERKEBUNAN NUSANTARA VI",
        parentCompanyName: "PERKEBUNAN NUSANTARA",
        address: "Ds. Sungai Kunyit, Kec Sangir Jujuan, Kab Solok, West Sumatera",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -1.52085, lng: 101.553368 },
        title: "Tidar Kerinci Agung",
        millCompanyName: "TIDAR KERINCI AGUNG",
        parentCompanyName: "TIRTA MAS",
        address: "Ds.Lubuk Besar, Kec.Asam Jujuhan, Dhamasraya, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -0.903777778, lng: 101.3981389 },
        title: "Sijunjung",
        millCompanyName: "KEMILAU PERMATA SAWIT",
        parentCompanyName: "SUPERVENTURE",
        address: "Jl. Koto Rona RT. RW. Muaro Takung Kec. Kamang Baru Kab. Sijunjung - West Sumatera",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: 0.324638889, lng: 99.45223333 },
        title: "Sawita Pasaman Jaya",
        millCompanyName: "SAWITA PASAMAN JAYA",
        parentCompanyName: "SRM",
        address: "Jorong Air Runding, Nagara ParitKec. Koto BalingkaKab. Pasaman Barat, Sumatera Barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -1.46771, lng: 101.51416 },
        title: "Kencana Sawit Indonesia",
        millCompanyName: "KENCANA SAWIT INDONESIA",
        parentCompanyName: "WILMAR INTERNATIONAL",
        address: "Ds.Sungai Kunyit, Kec.Sangir Jujuan, Solok Selatan, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -1.1498167, lng: 101.7401833 },
        title: "Damasraya Sawit Lestari",
        millCompanyName: "DAMASRAYA SAWIT LESTARI",
        parentCompanyName: "DAMASRAYA SAWIT LESTARI",
        address: "Baroe Kab.Dhamasraya Sumatera Barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -0.04939, lng: 99.8837 },
        title: "Sari Buah Sawit",
        millCompanyName: "SARI BUAH SAWIT",
        parentCompanyName: "SARI BUAH SAWIT",
        address: "Pasaman Barat, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -0.10169, lng: 100.05 },
        title: "Perkebunan Pelalu Raya",
        millCompanyName: "PERKEBUNAN PELALU RAYA",
        parentCompanyName: "PERKEBUNAN PELALU RAYA",
        address: "Kec.Palembayan, Agam, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: 0.198959, lng: 99.626588 },
        title: "Agrowiratama",
        millCompanyName: "AGROWIRATAMA",
        parentCompanyName: "MUSIM MAS",
        address: "Jorong Aie Aji, Nagari Sungai Aua, Kecamatan Sungai Aua, Kabupaten Pasaman Barat, Sumatera Barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: 0.01405, lng: 99.83695 },
        title: "Ophir",
        millCompanyName: "PERKEBUNAN NUSANTARA VI",
        parentCompanyName: "PERKEBUNAN NUSANTARA",
        address: "Ds.Sariak, Kec.Luhak Nan Duo, Pasaman Barat, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -0.31971, lng: 99.87707 },
        title: "Mutiara Agam",
        millCompanyName: "MUTIARA AGAM",
        parentCompanyName: "PROVIDENT AGRO",
        address: "Tiku V. Jorong, Tanjung Mutiara, Agam, Sumatra Barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: 0.121017, lng: 99.720883 },
        title: "Gersindo Minang Plantation",
        millCompanyName: "GERSINDO MINANG PLANTATION",
        parentCompanyName: "WILMAR INTERNATIONAL",
        address: "Ds.Tanjung Pangkal, Kec.Pasaman, Pasaman Barat, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: 0.229917, lng: 99.477083 },
        title: "Air Balam",
        millCompanyName: "BAKRIE PASAMAN PLANTATION",
        parentCompanyName: "BAKRIE SUMATERA PLANTATIONS",
        address: "Air Balam, Kec.Sei Beremas, Pasaman Barat, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -1.10739, lng: 101.51263 },
        title: "Andalas Wahana Berjaya",
        millCompanyName: "ANDALAS WAHANA BERJAYA",
        parentCompanyName: "TSH RESOURCES BERHAD",
        address: "Kab.Dharmasraya, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -0.05248, lng: 99.97282 },
        title: "Andalas Agro Industri",
        millCompanyName: "ANDALAS AGRO INDUSTRI",
        parentCompanyName: "TSH RESOURCES BERHAD",
        address: "Air Rau, Jorong Anam Koto Selatan, Nagari Kinali, Kecamatan Kinali, Kabupaten Pasaman Barat",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    },
    {
        position: { lat: -0.15489, lng: 100.02914 },
        title: "Agro Minang Perkasa",
        millCompanyName: "AGRO MINANG PERKASA",
        parentCompanyName: "WILMAR INTERNATIONAL",
        address: "Ds.Tapian Kandis, Kec.Palembayan, Agam, West Sumatra",
        province: "SUMATERA BARAT",
        farmArea: "(no data) ha",
        ffbProduction: "(no data) ton/year",
        facilityCapacity: "(no data) ton/hour",
        cpoProduction: "(no data) ton/year",
        pkProduction: "(no data) ton/year",
        description: "농장면적: (no data) ha, FFB 생산: (no data) ton/year, 설비 용량: (no data) ton/hour, CPO 생산: (no data) ton/year, PK 생산: (no data) ton/year.",
        markerIcon: "new_palm_tree.png"
    }
];
